#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/common.sh"

KEEPER="$SRC_DIR/src/hotspot/os/bsd/symbol_keeper.cpp"
SYMBOLS="$GEN_DIR/native-keep-symbols.txt"
LIBLIST="$GEN_DIR/native-keeper-input-libs.txt"

: > "$LIBLIST"
for lib in libjava.a libjimage.a libnet.a libnio.a libzip.a; do
  path="$STATIC_LIB_DIR/$lib"
  require_file "$path"
  echo "$path" >> "$LIBLIST"
done

# Add every static archive generated by jdk.crypto.cryptoki. Prefer the
# module-specific support/native tree because it avoids guessing the basename.
found_cryptoki=0
if [[ -d "$BUILD_DIR/support/native/jdk.crypto.cryptoki" ]]; then
  while IFS= read -r lib; do
    [[ -n "$lib" ]] || continue
    echo "$lib" >> "$LIBLIST"
    found_cryptoki=1
  done < <(find "$BUILD_DIR/support/native/jdk.crypto.cryptoki" -type f -name '*.a' -print | LC_ALL=C sort)
fi

if [[ "$found_cryptoki" -eq 0 ]]; then
  while IFS= read -r lib; do
    [[ -n "$lib" ]] || continue
    echo "$lib" >> "$LIBLIST"
    found_cryptoki=1
  done < <(find "$STATIC_LIB_DIR" -maxdepth 1 -type f -name '*pkcs11*.a' -print | LC_ALL=C sort)
fi

[[ "$found_cryptoki" -eq 1 ]] || die "cannot discover jdk.crypto.cryptoki native archive"

tmp="$GEN_DIR/native-symbols.raw"
: > "$tmp"

while IFS= read -r lib; do
  require_file "$lib"
  # Apple nm:
  #   -g external symbols only
  #   -U omit undefined symbols
  # Mach-O C symbols normally have a leading underscore; remove it below.
  xcrun nm -gU "$lib" 2>/dev/null | awk '{print $NF}' >> "$tmp" || \
    die "nm failed for $lib"
done < "$LIBLIST"

sed 's/^_//' "$tmp" \
  | grep -E '^(Java_|JNI_OnLoad|JNI_OnUnload|JIMAGE_|JDK_)' \
  | LC_ALL=C sort -u > "$SYMBOLS" || true

count="$(wc -l < "$SYMBOLS" | tr -d ' ')"
[[ "$count" -gt 0 ]] || die "generated native symbol keeper is empty"

{
  echo "/* Auto-generated. Do not edit."
  echo " * Inputs are listed in: $LIBLIST"
  echo " * Symbols are listed in: $SYMBOLS"
  echo " *"
  echo " * This file intentionally gives most selected native entries a generic"
  echo " * C function declaration. The functions are never called through this"
  echo " * declaration; only their addresses are placed in a relocation table."
  echo " *"
  echo " * Exception: the JIMAGE_* API is already declared (as real signatures)"
  echo " * in jimage.hpp, which is visible in this compilation unit via the"
  echo " * HotSpot include chain. Re-declaring them as void(void) would be an"
  echo " * overload conflict, so the real header is included instead."
  echo " */"
  echo
  if grep -q '^JIMAGE_' "$SYMBOLS"; then
    echo '#include "jimage.hpp"'
    echo
  fi
  echo 'extern "C" {'
  while IFS= read -r sym; do
    case "$sym" in
      JIMAGE_*) ;;
      *) printf 'void %s(void);\n' "$sym" ;;
    esac
  done < "$SYMBOLS"
  echo '}'
  echo
  echo '// Function pointers are cast to void* so entries with different real'
  echo '// signatures can share one relocation table.'
  echo 'static void* const tiny_kept_symbols[] = {'
  while IFS= read -r sym; do
    printf '  reinterpret_cast<void*>(&%s),\n' "$sym"
  done < "$SYMBOLS"
  echo '};'
  echo
  echo 'extern "C" void tiny_symbol_keeper_anchor() {'
  echo '  // One relocation from JNI_CreateJavaVM reaches this function; this'
  echo '  // inline-asm input keeps the table reachable without walking it.'
  echo '  __asm__ __volatile__("" : : "r"(tiny_kept_symbols) : "memory");'
  echo '}'
  echo
  echo 'extern "C" void loadfunctions() {'
  echo '  // Compatibility with the current ios-tools symbol keeper API.'
  echo '  tiny_symbol_keeper_anchor();'
  echo '}'
} > "$KEEPER"

cp "$KEEPER" "$GEN_DIR/symbol_keeper.cpp"
git -C "$SRC_DIR" diff -- src/hotspot/os/bsd/symbol_keeper.cpp > "$GEN_DIR/symbol_keeper.patch" || true

echo "Generated symbol keeper with $count symbols"
