#include "jvm_bridge.h"

#include <jni.h>

#include <cstdarg>
#include <pthread.h>

// Declared with C linkage at file scope instead of including <pthread.h>:
// the SDK guards this function behind availability macros that vary between
// macOS/iOS SDK generations.
extern "C" void pthread_jit_write_protect_np(int enabled) __API_AVAILABLE(macos(11.0), ios(14.0));
#include <arpa/inet.h>
#include <dlfcn.h>
#include <errno.h>
#include <netinet/in.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <sys/socket.h>
#include <sys/stat.h>
#include <unistd.h>

namespace {

JavaVM *g_vm = nullptr;
pthread_t g_thread = 0;
volatile bool g_running = false;
tinyvm_log_fn g_log_fn = nullptr;
tinyvm_exit_fn g_exit_fn = nullptr;
char g_err[512] = {0};

struct StartArgs {
  char runtime_home[1024];
  char jar_paths[2048];
  char user_home[1024];
};

void report_error(const char *fmt, ...) __attribute__((format(printf, 1, 2)));
void report_error(const char *fmt, ...) {
  va_list ap;
  va_start(ap, fmt);
  vsnprintf(g_err, sizeof(g_err), fmt, ap);
  va_end(ap);
}

void forward_log(const char *line) {
  if (g_log_fn != nullptr && line != nullptr) {
    g_log_fn(line);
  }
}

// Collects the system DNS servers and writes vproxy's resolver config to
// <user_home>/.vproxy/resolv.conf (vproxy reads ${user.home}/.vproxy/
// resolv.conf before /etc/resolv.conf). Sources, in order:
//   1. /etc/resolv.conf ("nameserver x.x.x.x" lines) - present on macOS
//      and therefore on the simulator.
//   2. libresolv's res_9_* functions via dlopen - for environments without
//      the file (real iOS devices); the symbols are resolved manually
//      because the SDK headers mark them unavailable for iOS.
// Any failure is reported with detail and stops the start; nothing is
// silently skipped.
bool write_resolv_conf(const char *user_home) {
  std::string servers;

  FILE *f = fopen("/etc/resolv.conf", "r");
  if (f != nullptr) {
    char line[512];
    while (fgets(line, sizeof(line), f) != nullptr) {
      char ip[256];
      if (sscanf(line, " nameserver %255s", ip) == 1) {
        servers += "nameserver ";
        servers += ip;
        servers += "\n";
      }
    }
    fclose(f);
  } else {
    forward_log("[native] /etc/resolv.conf not readable; trying libresolv");
  }

  if (servers.empty()) {
    // struct __res_9_state is not in the iOS SDK headers; the buffer below
    // is far larger than the actual struct. res_9_sockaddr_union holds a
    // sockaddr_storage; 128 bytes per slot is sufficient.
    typedef int (*ninit_t)(void *);
    typedef int (*getservers_t)(void *, void *, int);
    typedef void (*ndestroy_t)(void *);
    void *h = dlopen("libresolv.9.dylib", RTLD_LAZY);
    if (h == nullptr) {
      report_error("cannot collect DNS servers: /etc/resolv.conf missing/unreadable and dlopen(libresolv.9.dylib) failed: %s", dlerror());
      return false;
    }
    auto ninit = reinterpret_cast<ninit_t>(dlsym(h, "res_9_ninit"));
    auto getservers = reinterpret_cast<getservers_t>(dlsym(h, "res_9_getservers"));
    auto ndestroy = reinterpret_cast<ndestroy_t>(dlsym(h, "res_9_ndestroy"));
    if (ninit == nullptr || getservers == nullptr || ndestroy == nullptr) {
      report_error("cannot collect DNS servers: libresolv.9.dylib lacks res_9_* symbols");
      return false;
    }
    alignas(16) unsigned char state[4096];
    unsigned char addrs[16][128];
    memset(state, 0, sizeof(state));
    if (ninit(state) != 0) {
      report_error("cannot collect DNS servers: res_9_ninit failed");
      return false;
    }
    int n = getservers(state, addrs, 16);
    char buf[INET6_ADDRSTRLEN];
    for (int i = 0; i < n && i < 16; i++) {
      sockaddr *sa = reinterpret_cast<sockaddr *>(&addrs[i]);
      void *in;
      if (sa->sa_family == AF_INET) {
        in = &reinterpret_cast<sockaddr_in *>(sa)->sin_addr;
      } else if (sa->sa_family == AF_INET6) {
        in = &reinterpret_cast<sockaddr_in6 *>(sa)->sin6_addr;
      } else {
        continue;
      }
      if (inet_ntop(sa->sa_family, in, buf, sizeof(buf)) == nullptr) {
        continue;
      }
      servers += "nameserver ";
      servers += buf;
      servers += "\n";
    }
    ndestroy(state);
    if (servers.empty()) {
      report_error("no DNS servers found (/etc/resolv.conf and libresolv both gave nothing)");
      return false;
    }
  }

  std::string dir = std::string(user_home) + "/.vproxy";
  if (mkdir(dir.c_str(), 0755) != 0 && errno != EEXIST) {
    report_error("mkdir %s failed: %s", dir.c_str(), strerror(errno));
    return false;
  }
  std::string path = dir + "/resolv.conf";
  FILE *out = fopen(path.c_str(), "w");
  if (out == nullptr) {
    report_error("cannot write %s: %s", path.c_str(), strerror(errno));
    return false;
  }
  fputs("# generated by the Tiny Zero iOS demo before starting the JVM\n", out);
  fputs(servers.c_str(), out);
  if (fflush(out) != 0 || fclose(out) != 0) {
    report_error("writing %s failed: %s", path.c_str(), strerror(errno));
    return false;
  }
  std::string note = "[native] wrote " + path;
  forward_log(note.c_str());
  return true;
}

}  // namespace

// Called from Java via JNI: IosBootstrap.nativeLog(String).
// Must have external C linkage or the JNI lookup by name fails.
extern "C" JNIEXPORT void JNICALL Java_IosBootstrap_nativeLog(JNIEnv *env, jclass cls, jstring line) {
  (void)cls;
  if (line == nullptr) {
    return;
  }
  const char *utf = env->GetStringUTFChars(line, nullptr);
  if (utf != nullptr) {
    forward_log(utf);
    env->ReleaseStringUTFChars(line, utf);
  }
}

namespace {

void *jvm_thread_main(void *arg) {
  StartArgs args = *static_cast<StartArgs *>(arg);
  delete static_cast<StartArgs *>(arg);

  // Align the real per-thread MAP_JIT protection with what the server W^X
  // healing assumes as its initial state (_jit_exec_enabled == false, i.e.
  // write-enabled): on macOS 26 the system default is write-protected, and
  // the healing's own enable/disable calls are compiled out for iOS targets
  // unless patched for the simulator (see support/build-sim-jvm.sh).
  pthread_jit_write_protect_np(0);

  // NOTE: -Djava.home is deliberately NOT passed: hotspot's os_bsd.cpp
  // (__IOS__ + statically linked) derives java_home = <executable dir>/lib
  // and overrides the property, so the runtime image must simply be placed
  // at <bundle>/lib/lib/modules.
  (void)args.runtime_home;
  JavaVMOption options[17];
  std::string cp = std::string("-Djava.class.path=") + args.jar_paths;
  // vproxy stores its state below ${user.home}; pointing it at the app
  // container keeps everything inside the sandbox.
  std::string userHomeOpt = std::string("-Duser.home=") + args.user_home;
  options[0].optionString = const_cast<char *>(cp.c_str());
  options[1].optionString = const_cast<char *>("-Xrs");
  options[2].optionString = const_cast<char *>("-Djava.awt.headless=true");
  // Match the Tiny Zero device configuration (SerialGC); the default G1
  // hits a ShouldNotCall() in the Zero signal path during early VM init.
  options[3].optionString = const_cast<char *>("-XX:+UseSerialGC");
  // Interpreter only: the JIT compiler threads writing the code cache race
  // with the lazy per-thread W^X flipping; -Xint removes that concurrency
  // while validating the embedding.
  options[4].optionString = const_cast<char *>("-Xint");
  // Explicit null checks in generated code: implicit (SIGSEGV-based) null
  // checks cannot be recovered on the Darwin zero/simulator signal paths.
  options[5].optionString = const_cast<char *>("-XX:+UnlockDiagnosticVMOptions");
  options[6].optionString = const_cast<char *>("-XX:-ImplicitNullChecks");
  // Compact object headers change the object header layout used by the
  // generated vtable/type-check stubs; keep the classic layout while
  // validating the simulator embedding.
  options[7].optionString = const_cast<char *>("-XX:-UseCompactObjectHeaders");
  // The runtime image was produced without a CDS archive; make sure the
  // sharing machinery stays off so method entry state is linked normally.
  options[8].optionString = const_cast<char *>("-Xshare:off");
  // Bootstrap on the zero interpreter allocates heavily before VM init
  // completes; a larger young gen avoids "GC triggered before VM
  // initialization completed".
  options[9].optionString = const_cast<char *>("-Xms4g");
  // The zero interpreter recurses through C++ frames per Java call; deep
  // <clinit> chains during bootstrap overflow the default stack.
  options[10].optionString = const_cast<char *>("-Xss32m"); // zero recurses per Java call
  // Bootstrap on this port cannot fill stack traces yet (backtrace fields
  // are null before the stack machinery initializes); disable collection.
  options[11].optionString = const_cast<char *>("-XX:-StackTraceInThrowable");
  // Avoid mixing rewritten and non-rewritten bytecode states across the
  // on-demand linking during bootstrap.
  options[12].optionString = const_cast<char *>("-XX:-RewriteBytecodes");
  options[13].optionString = const_cast<char *>("-XX:NewSize=1536m");
  // No attach mechanism in the demo; avoids the ".java_pidNNN: file name is
  // too long" warning in the deep simulator sandbox path.
  options[14].optionString = const_cast<char *>("-XX:+DisableAttachMechanism");
  options[15].optionString = const_cast<char *>(userHomeOpt.c_str());
  // vproxy's own suggestion at startup: enables its JDKUnsafe path instead
  // of falling back with a reflection warning.
  options[16].optionString = const_cast<char *>("--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED");
  JavaVMInitArgs vm_args = {};
  vm_args.version = JNI_VERSION_1_8;
  vm_args.nOptions = 17;
  vm_args.options = options;
  vm_args.ignoreUnrecognized = JNI_FALSE;

  JNIEnv *env = nullptr;
  jint rc = JNI_CreateJavaVM(&g_vm, reinterpret_cast<void **>(&env), &vm_args);
  if (rc != JNI_OK) {
    report_error("JNI_CreateJavaVM failed with %d", rc);
    if (g_exit_fn) g_exit_fn(1, g_err);
    g_running = false;
    return nullptr;
  }
  forward_log("[native] JVM created (Zero, java.home set)");

  // 1) Bootstrap helper: register nativeLog and redirect stdout/stderr, so
  // everything vproxy logs reaches the app UI. Without this step the JVM
  // would be completely silent.
  jclass boot = env->FindClass("IosBootstrap");
  if (boot == nullptr) {
    env->ExceptionClear();
    report_error("FindClass(IosBootstrap) failed; vproxy-ios-bootstrap.jar on java.class.path?");
    g_vm->DestroyJavaVM();
    g_vm = nullptr;
    if (g_exit_fn) g_exit_fn(1, g_err);
    g_running = false;
    return nullptr;
  }
  {
    // Application classes resolve natives through their class loader (the
    // Java ClassLoader.findNative path), which finds nothing in a fully
    // static build; register the bridge's native method explicitly.
    JNINativeMethod method;
    method.name = const_cast<char*>("nativeLog");
    method.signature = const_cast<char*>("(Ljava/lang/String;)V");
    method.fnPtr = reinterpret_cast<void*>(&Java_IosBootstrap_nativeLog);
    if (env->RegisterNatives(boot, &method, 1) != JNI_OK) {
      report_error("RegisterNatives(IosBootstrap.nativeLog) failed");
      env->ExceptionDescribe();
      env->ExceptionClear();
      g_vm->DestroyJavaVM();
      g_vm = nullptr;
      if (g_exit_fn) g_exit_fn(1, g_err);
      g_running = false;
      return nullptr;
    }
    jmethodID redirect = env->GetStaticMethodID(boot, "redirect", "()V");
    if (redirect == nullptr) {
      report_error("GetStaticMethodID(IosBootstrap.redirect) failed");
      env->ExceptionClear();
      g_vm->DestroyJavaVM();
      g_vm = nullptr;
      if (g_exit_fn) g_exit_fn(1, g_err);
      g_running = false;
      return nullptr;
    }
    env->CallStaticVoidMethod(boot, redirect);
  }

  // 2) vproxy: the jar's Main-Class (see META-INF/MANIFEST.MF).
  jclass clazz = env->FindClass("io/vproxy/app/app/Main");
  if (clazz == nullptr) {
    env->ExceptionClear();
    report_error("FindClass(io/vproxy/app/app/Main) failed; vproxy.jar on java.class.path?");
    if (env->ExceptionCheck()) env->ExceptionDescribe();
    g_vm->DestroyJavaVM();
    g_vm = nullptr;
    if (g_exit_fn) g_exit_fn(1, g_err);
    g_running = false;
    return nullptr;
  }

  jmethodID main = env->GetStaticMethodID(clazz, "main", "([Ljava/lang/String;)V");
  if (main == nullptr) {
    report_error("GetStaticMethodID(io.vproxy.app.app.Main.main) failed");
    g_vm->DestroyJavaVM();
    g_vm = nullptr;
    if (g_exit_fn) g_exit_fn(1, g_err);
    g_running = false;
    return nullptr;
  }

  // -Deploy=helloworld as a program argument, exactly like the documented
  // `java -jar vproxy.jar -Deploy=helloworld` launch (MainUtils converts
  // -Dkey=value arguments into system properties).
  jclass stringClass = env->FindClass("java/lang/String");
  jobjectArray jargs = env->NewObjectArray(1, stringClass, nullptr);
  env->SetObjectArrayElement(jargs, 0, env->NewStringUTF("-Deploy=helloworld"));

  env->CallStaticVoidMethod(clazz, main, jargs);
  if (env->ExceptionCheck()) {
    report_error("io.vproxy.app.app.Main threw an exception (see log above)");
    env->ExceptionDescribe();
    env->ExceptionClear();
  }

  g_vm->DestroyJavaVM();
  g_vm = nullptr;
  forward_log("[native] JVM destroyed");
  g_running = false;
  if (g_exit_fn) g_exit_fn(0, "main returned");
  return nullptr;
}

}  // namespace

extern "C" int tinyvm_start(const char *runtime_home, const char *jar_paths, const char *user_home,
                            tinyvm_log_fn log_fn, tinyvm_exit_fn exit_fn) {
  if (g_running) {
    report_error("JVM already running");
    return 1;
  }
  if (runtime_home == nullptr || jar_paths == nullptr || user_home == nullptr) {
    report_error("null argument");
    return 1;
  }

  g_err[0] = '\0';
  g_log_fn = log_fn;
  g_exit_fn = exit_fn;

  // Before the JVM starts: collect DNS servers and write
  // <user_home>/.vproxy/resolv.conf, so vproxy's resolver has servers on
  // both simulator (macOS /etc/resolv.conf) and device (libresolv).
  if (!write_resolv_conf(user_home)) {
    return 1;
  }

  StartArgs *args = new StartArgs();
  snprintf(args->runtime_home, sizeof(args->runtime_home), "%s", runtime_home);
  snprintf(args->jar_paths, sizeof(args->jar_paths), "%s", jar_paths);
  snprintf(args->user_home, sizeof(args->user_home), "%s", user_home);

  g_running = true;
  if (pthread_create(&g_thread, nullptr, jvm_thread_main, args) != 0) {
    report_error("pthread_create failed");
    g_running = false;
    return 1;
  }
  return 0;
}

extern "C" int tinyvm_stop(int timeout_seconds) {
  if (!g_running || g_vm == nullptr) {
    return 0;
  }
  // Stop without any program cooperation: call System.exit(0) from the
  // host — the whole process exits with its shutdown hooks, which is the
  // natural lifecycle for a plain Java program. java.lang.System is a
  // bootstrap class, so FindClass works from any attached thread.
  // System.exit runs on its own thread because this mobile snapshot's exit
  // path can deadlock the calling thread inside Runtime.exit (logging).
  // The host only observes: if the exit does not complete (an upstream,
  // intermittent exit-path stall) it reports an error and never forces.
  forward_log("[native] stop: stage 1 System.exit(0)");
  pthread_t exit_thread;
  pthread_create(&exit_thread, nullptr, [](void*) -> void* {
    JNIEnv *env = nullptr;
    if (g_vm != nullptr && g_vm->AttachCurrentThread(reinterpret_cast<void **>(&env), nullptr) == JNI_OK) {
      jclass system = env->FindClass("java/lang/System");
      if (system != nullptr) {
        jmethodID exit = env->GetStaticMethodID(system, "exit", "(I)V");
        if (exit != nullptr) {
          env->CallStaticVoidMethod(system, exit, 0);
        }
      }
      if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
      }
      g_vm->DetachCurrentThread();
    }
    return nullptr;
  }, nullptr);
  pthread_detach(exit_thread);

  // Observe, never force: a healthy System.exit removes the whole process
  // before this loop finishes. If the upstream exit path stalls (see README
  // §6: intermittent, not reproducible on the current build), report and
  // leave the process alive — the user closes the app manually.
  for (int i = 0; i < timeout_seconds * 10 && g_running; i++) {
    usleep(100 * 1000);
  }
  if (g_running) {
    report_error("System.exit did not complete within %ds (upstream exit-path stall)", timeout_seconds);
    return 1;
  }
  return 0;
}

extern "C" bool tinyvm_is_running(void) { return g_running; }

extern "C" const char *tinyvm_last_error(void) { return g_err; }
