#!/usr/bin/env bash
set -euo pipefail

# Build a Zero JVM static library for the iOS Simulator (arm64).
#
# Builds in the same repository working tree as the device pipeline (a
# separate configure conf), reusing the generated symbol_keeper.cpp, so the
# simulator slice behaves like the device slice. All port fixes are merged
# into the repository (see the presence check below). The runtime image
# (lib/modules) is platform independent; it is built from THIS build's
# exploded classes so it always matches the simulator sources.

DEMO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TINY_ROOT="${TINY_ROOT:-$DEMO_ROOT/../tiny-zero-ios-build}"
# shellcheck disable=SC1091
source "$TINY_ROOT/config/build.env"
# shellcheck disable=SC1091
source "$TINY_ROOT/scripts/lib/port-fixes.sh"
# shellcheck disable=SC1091
source "$TINY_ROOT/scripts/lib/runtime-image.sh"

SRC="$(cd "$TINY_ROOT/.." && pwd)"

CONF=ios-aarch64-zero-sim-release
SIMSDK="$(xcrun --sdk iphonesimulator --show-sdk-path)"
SIMFFI="$HOME/ios-sim-support/libffi"
[[ -f "$SIMFFI/lib/libffi.a" ]] || { echo "ERROR: simulator libffi missing at $SIMFFI" >&2; exit 1; }

mkdir -p "$TINY_ROOT/work/logs"
cd "$SRC"

# The port fixes (sim MAP_JIT, zero interpreter entry fallback + on-demand
# linking, Throwable pre-init guard, RTLD_DEFAULT static native lookup,
# bsd_zero crash pc, lazy W^X in the signal handler) are merged into this
# repository - git history is the single source of truth, nothing is patched
# here anymore. Fail fast with a concrete remedy on a too-old tree.
check_port_fixes "$SRC"

# The symbol keeper in the tree must be the precise one generated by the
# device pipeline (Pass 2), not the Pass-1 stub: with the stub, the final
# link keeps no JNI symbols and the app fails native resolution at runtime.
KEEPER="$SRC/src/hotspot/os/bsd/symbol_keeper.cpp"
if ! grep -q 'tiny_kept_symbols' "$KEEPER" 2>/dev/null; then
  echo "ERROR: $KEEPER is missing or still the Pass-1 stub." >&2
  echo "       Run tiny-zero-ios-build/build.sh first; it generates the precise keeper." >&2
  exit 1
fi

# Invalidate the configuration if it was produced before the assembler flags
# fix (copy_bsd_aarch64.S used to compile to a macOS object because the .S
# step missed -target/-isysroot) or points at an SDK that no longer exists.
if [[ -f "build/$CONF/spec.gmk" ]] && ! grep -q "arm64-apple-ios14.5-simulator" build/$CONF/spec.gmk; then
  echo "stale configuration (SDK/asflags changed), reconfiguring..."
  rm -rf "build/$CONF"
fi

if [[ ! -f "build/$CONF/spec.gmk" ]]; then
  # JFR is disabled: it has no BSD SystemProcessInterface implementation
  # and the demo does not need it.
  bash configure \
    --with-conf-name="$CONF" \
    --with-debug-level=release \
    --disable-warnings-as-errors \
    --disable-precompiled-headers \
    --openjdk-target=aarch64-macos-ios \
    --with-jvm-variants=zero \
    --with-jvm-features="-jfr" \
    --with-native-debug-symbols=none \
    --enable-headless-only \
    --with-boot-jdk="$BOOT_JDK" \
    --with-libffi-include="$SIMFFI/include" \
    --with-libffi-lib="$SIMFFI/lib" \
    --with-cups-include="$CUPS_INCLUDE" \
    --with-sysroot="$SIMSDK" \
    --with-extra-asflags="-target arm64-apple-ios14.5-simulator -isysroot $SIMSDK" \
    2>&1 | tee "$TINY_ROOT/work/logs/configure-sim.log"
fi

make LOG=info JOBS="$JOBS" CONF="$CONF" static-libs-image jdk.unsupported-java

STATIC="build/$CONF/images/static-libs/lib"
for lib in "${TINY_BASE_STATIC_LIBS[@]}"; do
  [[ -f "$STATIC/$lib" ]] || { echo "ERROR: $STATIC/$lib missing" >&2; exit 1; }
done
[[ -f "$STATIC/zero/libjvm.a" ]] || { echo "ERROR: simulator libjvm.a missing" >&2; exit 1; }

cryptoki_libs=()
while IFS= read -r lib; do
  [[ -n "$lib" ]] && cryptoki_libs+=("$lib")
done < <(print_cryptoki_archives "build/$CONF" "$STATIC")
[[ ${#cryptoki_libs[@]} -gt 0 ]] || { echo "ERROR: no cryptoki archive" >&2; exit 1; }

mkdir -p "$DEMO_ROOT/third_party"
libtool -static -o "$DEMO_ROOT/third_party/libtinyjvm-sim.a" \
  "$STATIC/zero/libjvm.a" \
  "$SIMFFI/lib/libffi.a" \
  "${TINY_BASE_STATIC_LIBS[@]/#/$STATIC/}" \
  "${cryptoki_libs[@]}"

# Runtime image: same jmod/jlink contract workarounds as the device pipeline
# (shared in tiny-zero-ios-build/scripts/lib/runtime-image.sh), then the full
# <bundle>/lib tree including conf/, lib/tzdb.dat and the builtin-lib marker
# files (0-byte libjimage.dylib/libj2pkcs11.dylib route System.loadLibrary of
# the statically linked internal libraries through findBuiltinLib and skip
# dlopen entirely).
mkdir -p "$DEMO_ROOT/work-generated"
sync_jmod_release_descriptor "build/$CONF/jdk/modules" "$BOOT_JDK" \
  "$DEMO_ROOT/work-generated/sim-host-release"
create_module_jmods "build/$CONF/jdk/modules" "$DEMO_ROOT/work-generated/sim-jmods" "$BOOT_JDK"
jlink_tiny_runtime "$DEMO_ROOT/work-generated/sim-jmods" \
  "$DEMO_ROOT/work-generated/sim-runtime" "$BOOT_JDK"
stage_runtime_lib "$DEMO_ROOT/work-generated/sim-runtime" "$BOOT_JDK" \
  "$DEMO_ROOT/third_party/lib"

echo "OK: $DEMO_ROOT/third_party/libtinyjvm-sim.a"
